rsl150101/NoAFK

- README.md
> [테스트] 풀리퀘 테스트

- README.md
> Revert "[테스트] 풀리퀘 테스트"

- src/controllers/api.controller.js
- src/middlewares/auth.js
- src/passport/index.js
- src/repositories/users.repository.js
- src/routes/page.routes.js
- src/services/users.service.js
- src/static/js/join.js
- src/utility/customError.js
- src/views/join.html
객체구조분해할당, 에러핸들링 클래스명 PascalCase로 변경, 닷노테이션 클린업
> [병합] 튜터님 피드백 적용

- src/controllers/comments.controller.js
- src/controllers/projects.controller.js
- src/repositories/comments.repository.js
- src/repositories/projects.repository.js
- src/routes/page.routes.js
- src/routes/projects.routes.js
- src/services/comments.service.js
- src/services/projects.service.js
- src/static/css/projectDetail.css
- src/views/projectDetail.html
projects.routes, controller, service, repository :  공고 상세보기, 수정, 삭제 API
comments.controller, service, repository  :  댓글 CRUD기능
> [병합] 공고 상세보기 페이지 기능

- src/migrations/20230228073808-create-user.js
- src/models/project.js
- src/models/user.js
User 모델 testResult STRING 수정
Project 모델 owner 추가, status, recommendLevel: defaultValue = 0 설정
> [수정] DB 모델 수정(User, project)

- src/controllers/api.controller.js
- src/controllers/comments.controller.js
- src/controllers/projects.controller.js
- src/controllers/teams.controller.js
- src/middlewares/auth.js
- src/passport/index.js
- src/repositories/comments.repository.js
- src/repositories/teams.repository.js
- src/repositories/users.repository.js
- src/routes/page.routes.js
- src/routes/projects.routes.js
- src/services/comments.service.js
- src/services/teams.service.js
- src/services/users.service.js
- src/static/js/projectEditModal.js
- src/utility/customError.js
- src/views/projectDetail.html
1.  공고 상세보기 페이지 구현 완료
2.  auth 관련 기능 refresh token 추가해서 수정
> [병합] auth페이지, 상세페이지 완

- src/controllers/teams.controller.js
- src/models/projectUser.js
- src/repositories/teams.repository.js
- src/repositories/users.repository.js
- src/routes/page.routes.js
- src/routes/teams.routes.js
- src/services/teams.service.js
- src/static/js/myteam/teamAddNew.js
- src/static/js/myteam/teamEditMember.js
- src/views/myteam.html
[수정] 
- teams.controller의 getTeam -> renderTeamPage 로 이름변경, 
- includes 사용한 로직으로 변경, 
- 기존 라우터에서 삭제 ->  페이지라우터에 추가, 
- 넌적스템플릿 myteam.html 수정,
- 코드가독성을 위한 몇가지 자잘한 수정들.
> [병합] 페이지라우터 수정, 렌더링 메서드 이름 변경

- src/controllers/projects.controller.js
- src/middlewares/auth.js
- src/static/css/projectDetail.css
- src/static/js/projectDetail.js
- src/views/projectDetail.html
1. projectDetail.html - id 값에 댓글 별 아이디 값 추가
2. 로그인이 되어있지 않을 경우 신청하기 누르면 로그인 페이지로 가도록
3. auth.js - 미들웨어 수정 (쿠키가 없을 경우 로그인 페이지로 가는 것이 아니라 다음 코드로 넘어가도록)
4. projects.controller.js - 미들웨어에서 넘어온 값이 없는 경우 loginUserNickname에 null값 주기
> [병합] 공고 상세 페이지 디테일 수정

- src/controllers/api.controller.js
- src/controllers/users.controller.js
- src/middlewares/uploads.js
- src/repositories/teams.repository.js
- src/repositories/users.repository.js
- src/routes/page.routes.js
- src/routes/users.routes.js
- src/services/users.service.js
- src/static/css/mypage.css
- src/static/css/test.css
- src/static/js/mypage.js
- src/static/js/test.js
- src/views/mypage.html
- src/views/test.html
[마이페이지] S3 프로필 이미지 연결 완료.
[마이페이지] "home -> mypage" 프론트 경로 요청.
[테스트] 상태바 애니메이션 삭제.
> [수정] 마이페이지, 테스트 프론트 재구성 및 기능 연결

- src/controllers/projects.controller.js
- src/repositories/projects.repository.js
- src/services/projects.service.js
- src/static/js/adminProjectsSection.js
- src/static/js/cursorPagination.js
- src/views/adminProjects.html
- src/views/projects.html
모집 공고 페이지 및 백오피스 공고 관리 검색 관련 프론트 수정
커서 및 오프셋 기반 검색 기능 추가
> [병합] 커서 및 오프셋 기반 검색 추가된 페이지네이션과 관련 페이지 프론트

- src/controllers/projects.controller.js
- src/controllers/teams.controller.js
- src/repositories/teams.repository.js
- src/repositories/users.repository.js
- src/services/teams.service.js
- src/static/css/myteam.css
- src/utility/customError.js
> [병합] 팀원 추가시 밸리데이션 기능 구현

- src/repositories/teams.repository.js
- src/static/js/mypage.js
- src/views/mypage.html
Project 테이블의 owner가 userId로 변경되어 Number값으로 변환됨에 따라 
owner 부분을 기존과 동일하게 볼 수 있도록 수정하였습니다.
> [수정] 프로젝트 owner를 해당 유저의 닉네임으로 변경

- src/middlewares/auth.js
> [병합] checkLogin 미들웨어 수정

- src/static/css/mypage.css
마이페이지 화면 축소 시 개인정보 화면 가로줄 길이 화면 비율에 맞게 수정
> [수정] mypage CSS 수정

- README.md
> [병합] 리드미 수정

- src/controllers/projects.controller.js
- src/services/projects.service.js
- src/services/users.service.js
- src/utility/customError.js
> [병합] 공고 상세 페이지 수정

- src/models/user.js
user 모델 리프레쉬토큰 redis 으로 변경해서 사용 안함
> [삭제] user 모델 리프레쉬토큰 사용안해서 삭제

- src/static/css/projectDetail.css
- src/views/projectDetail.html
> [병합] 공고상세페이지 프론트 수정

- src/static/css/projectDetail.css
> [병합] 공고상세페이지 수정

- src/views/projectDetail.html
로그인 전 댓글 작성 칸 로그인 후 사용가능하다고 프론트 수정
> [수정] 공고 상세페이지 수정

- src/views/projectDetail.html
> [병합] 공고 상세페이지 수정

- .github/workflows/main.yml
- src/static/css/projectDetail.css
> [병합] 공고 상세페이지 수정 + 액션 수정

- src/static/css/projectDetail.css
> [병합] 공고상세페이지 css 수정

- src/controllers/projects.controller.js
- src/repositories/projects.repository.js
- src/repositories/teams.repository.js
- src/routes/api.routes.js
- src/routes/projects.routes.js
- src/services/projects.service.js
- src/static/js/projectDetail.js
- src/views/projectDetail.html
> [병합] Feature/project detail

- src/controllers/teams.controller.js
- src/repositories/teams.repository.js
- src/routes/teams.routes.js
- src/services/teams.service.js
- src/static/js/mypage.js
- src/static/js/myteam/teamAddNew.js
- src/static/js/projectDetail.js
- src/views/join.html
- src/views/myTeamList.html
- src/views/myteam.html
학수님 코드 에러핸들링 추가
에러나는 코드 수정
project 상태 관련 코드 수정 0: 모집중
팀원 추가, 방출 코드 수정 + 프론트단 메시지 수정
팀 삭제한 경우 프로젝트 상태를 0으로 바꾸고, 팀에 있는 유저들 삭제
projectUser테이블에 userId가 동일한 팀이 없으면 팀을 찾을 수 없도록...등등
> [병합] 팀 관련 코드 수정

- src/app.js
- src/controllers/teams.controller.js
- src/static/js/chatting.js
- src/views/myteam.html
> [병합] 코드 수정

- src/services/users.service.js
> [병합] 회원가입 인증번호 숫자만

- src/controllers/api.controller.js
- src/middlewares/auth.js
- src/static/js/join.js
> [병합] clearcookie

- src/static/js/projectAddModal.js
- src/views/partials/page-footer.html
- src/views/partials/project-add-modal.html
[추가] 모집 공고 등록 날짜 프론트에서 유효성 검사
[수정] page-footer 작동하지 않는 링크 제거 및 수정
> [병합] 모집 공고 등록 날짜 프론트에서 유효성 검사 추가, 작동하지 않는 링크 제거 및 수정

- README.md
- src/controllers/projects.controller.js
- src/controllers/teams.controller.js
- src/passport/index.js
- src/repositories/teams.repository.js
- src/routes/projects.routes.js
- src/services/teams.service.js
- src/static/js/projectDetail.js
- src/views/projectDetail.html
1.  카카오에 이메일이 존재하지 않는 경우 코드 수정
2.  공고 상세 페이지에서 신청 취소 기능 추가
3. 리드미 배포주소 수정
> [병합] 피드백 수정

- src/controllers/projects.controller.js
- src/controllers/teams.controller.js
- src/services/teams.service.js
- src/views/deletedTeam.html
> [병합] 프로젝트와 팀렌더 에러 프론트 수정

- src/static/css/mypage.css
- src/views/mypage.html
.png 업로드 이슈 해결 및 흰색 이미지 구분을 위한 이미지 테두리 추가
> [수정] 이미지 관련 테두리 추가

- src/controllers/users.controller.js
> [수정] 이미지 저장경로 수정

- src/controllers/comments.controller.js
- src/controllers/projects.controller.js
- src/controllers/teams.controller.js
- src/repositories/comments.repository.js
- src/routes/projects.routes.js
- src/services/comments.service.js
- src/services/teams.service.js
- src/static/js/myteam/teamUpdateStatus.js
- src/static/js/projectDetail.js
- src/utility/customError.js
- src/views/deletedTeam.html
- src/views/projectDetail.html
1. 팀 상태 전 단계로 수정 못하게 막음
2. 댓글이 더 없는 경우 더보기 없애기(limit배수인 경우 더보기가 뜨는 에러있었음)
3. 댓글 최신순 정렬
> [병합] 팀 상태, 댓글 수정

- src/middlewares/auth.js
- src/services/users.service.js
1. 액세스 토큰 유효시간 6시간->2시간
2. 액세스 토큰 값 보안을 위해 id값만
3.  토큰 중 하나라도 있으면 토큰 재발급 코드 수정
> [병합] 토큰 수정

- src/repositories/teams.repository.js
- src/views/allteam.html
1.  팀 페이지 프로젝트 진행 상태 오류 수정
2.  나의 팀에서 신청했을때에도 팀 열람이 가능한 오류 수정
> [병합] 팀 페이지 피드백 반영

- src/controllers/teams.controller.js
- src/repositories/projects.repository.js
- src/repositories/teams.repository.js
- src/services/teams.service.js
- src/static/css/myTeamList.css
- src/views/myTeamList.html
- 참가중인 팀 없을시 서버사이드 렌더링 구현
- 참가 신청한 팀 목록 서버사이드 렌더링 구현
- 참가 신청한 팀 목록과 공고페이지 링크 연결
- 참가 신청한 팀 없을시 서버사이드 렌더링 구현
- 나의 팀 목록 페이지 스타일 추가
> [병합] 나의 팀 목록 페이지 개선

- src/static/js/mypage.js
프론트에는 닉네임, 패스워드의 잘못된 입력에 따른 안내가 부족하여, 기능이 동작한 것  같지 않다라는 피드백이 있어 프론트 유효성 검사를 도입하여 변경에 대한 안내를 추가하였습니다.
피드백 : 닉네임변경이 다른 플랫폼에서는 동작하지 않는다.
개선 : 프론트 유효성 검사를 통해 올바른 입력 값을 넣도록 안내. (모든 플랫폼에서 기능 동작 확인)
> [수정] 피드백 반영 닉네임, 패스워드 유효성검사(프론트)

- src/static/js/join.js
1. 이메일을 바꾼 다음에도 인증번호 동일하게 사용해서 회원가입 가능한 거 수정
2. 회원가입 후 나가기 알림창 안 뜨도록 코드 수정
> [병합] 회원가입 오류 수정

- src/models/user.js
> [추가] DB USER 모델 private 항목

- src/repositories/teams.repository.js
- src/static/js/chatting.js
- src/static/js/myteam/teamEditMember.js
- src/views/myteam.html
- 리더 직책 수정시 권한에 따른 렌더링 오류 개선
- innerHTML -> insertAdjacentHTML 변경
- 리더 직책 수정 불가로 변경
> [병합] 팀관리페이지 권한 렌더링 개선

- src/controllers/teams.controller.js
- src/repositories/teams.repository.js
> [병합] sequelize Op 수정

- src/controllers/projects.controller.js
- src/controllers/users.controller.js
- src/models/user.js
- src/repositories/users.repository.js
- src/routes/projects.routes.js
- src/static/css/mypage.css
- src/static/js/mypage.js
- src/views/mypage.html
innerHTML 삭제 및 변경
private -> privateEmail
> [수정] 마이페이지 프로젝트 및 모델 이름 수정

- src/repositories/users.repository.js
privateEmail 기능에 동작 오류가 있어 수정하였습니다.
> [수정] privateEmail 기능동작 수정

- src/controllers/projects.controller.js
> [병합] 페이지 수정

- src/controllers/users.controller.js
- src/static/js/mypage.js
기존 : true -> 비공개, false -> 공개
변경 : true -> 공개, false -> 비공개
> [수정] privateEmail true-false 교체

- src/static/css/myteam.css
> [병합] td 태그 변경에 따른 css 수정

- package-lock.json
- package.json
- src/middlewares/limit.js
- src/routes/projects.routes.js
- src/static/css/style.css
- src/static/js/projectAddModal.js
[수정] 404.css -> err404.css 수정으로 인한 style.css import 수정
[추가] express-rate-limit 패키지 
[추가] IP 당 공고 등록 시간 및 갯수 제한 미들웨어
> [병합] css import 수정, 공고 등록 제한 미들웨어 추가

- src/controllers/api.controller.js
- src/services/users.service.js
- src/static/css/screen/pw-reissue-modal-screen.css
- src/static/js/join.js
- src/static/js/login.js
- src/views/partials/pw-reissue-modal.html
[수정] 쿠키사용대신 JSON으로 프론트에 인증번호 전송
[추가] 비밀번호 재발급 시 이메일 인증 기능 추가
[수정] css 수정
> [병합] 인증번호 기능

- src/controllers/projects.controller.js
- src/repositories/projects.repository.js
- src/routes/api.routes.js
- src/services/projects.service.js
- src/static/js/cursorPagination.js
- src/views/projects.html
[수정] 여러명이 같은 프로젝트 좋아요 눌렀을 때 버그 수정
[추가] 해당 유저의 프로젝트 좋아요 전체 조회 기능
[수정] 프로젝트 좋아요 버그 수정으로 인한 프론트 및 백 수정
> [수정] 프로젝트 좋아요 버그 수정

- src/controllers/teams.controller.js
- src/views/myteam.html
> [병합] 팀원초대시 수락 거절 렌더링 오류 개선

- src/repositories/users.repository.js
- src/services/users.service.js
- src/static/js/login.js
- src/views/members.html
- [수정] 이메일 인증 안 한 경우 메시지 출력
- [수정] 유저조회에서 이메일 조회시 비공개된 이메일도 가져오는 문제 수정
- [수정] 비공개 및 미완료 서버에서 처리
> [병합] 피드백 반영(이메일 비공개 조회)

- src/static/js/myteam/teamEditMember.js
> [병합] 팀원정보 수정시 오류 수정

- src/static/js/myteam/teamEmit.js
- src/static/js/myteam/teamUpdateStatus.js
> [병합] 팀진행상태 변경시 한번 더 묻기 추가

- src/services/teams.service.js
- src/static/js/myteam/teamDelete.js
> [병합] 팀삭제 기능 오류 개선

- src/services/users.service.js
- src/static/css/screen/admin-users-screen.css
- [추가] 차단된 유저 권한등급 차단으로 표시
- [추가] 현 페이지 위치 표시
> [병합] 회원관리 페이지 프론트 요소 추가
